language: java
# run on xvfb screen.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: "mvn -Dtest=\!GuiControllerTest.java clean test"
notifications:
  email:
    on_success: never
    on_failure: always
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
