language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "mvn clean test"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
# setup jobs.
env:
  - USE_FRAMEBUFFER=true
  - USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
