language: java
# run on xvfb screen.
before_install:
  - if [ $USE_FRAMEBUFFER = "true" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi
script: "mvn clean test"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer